ARGS=-lglut -lGLU -lGL -Wall -lm
CC=gcc

all: Exe1 Exe2 Exe3 Exe4 Exe5 Exe6 Exe7

Exe1:
	$(CC) Exe01.c -o 1gl $(ARGS)

Exe2:
	$(CC) Exe02.c -o 2gl $(ARGS)

Exe3:
	$(CC) Exe03.c -o 3gl $(ARGS)

Exe4:
	$(CC) Exe04.c -o 4gl $(ARGS)

Exe5:
	$(CC) Exe05.c -o 5gl $(ARGS)

Exe6:
	$(CC) Exe06.c -o 6gl $(ARGS)

Exe7:
	$(CC) Exe07.c -o 7gl $(ARGS)
